name: Go Tests
on: [push]
jobs:
  test-coverage:
    name: test/coverage
    runs-on: ubuntu-latest
    env:
      TLACFG: ${{ secrets.TLACFG }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Calc Coverage
      run: go test -v ./... -covermode=count -coverprofile=coverage.out
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
